title: Boris Vuković # your name (or website title) here
logo: "/images/logo.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have experience in the production of audiovisual works in both student and professional productions in various roles. 
  <br><br>
  Through education, I have earned the academic title of bachelor of arts in film and television directing and the academic title of master of comparative literature. I also passed various courses and workshops, including the 'Narrative + Game Design' course at the Machina Game Dev Academy in Zagreb and the 'Unity Developer' course at the PISMO Incubator in Novska, Croatia. 
  <br><br>
  <a href="https://www.linkedin.com/in/boris-vukovi%C4%87-505b52235/">View My LinkedIn Profile</a> 
 
 
